services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: marie-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-marie_erp}
      MYSQL_USER: ${DB_USER:-marie_user}
      MYSQL_PASSWORD: ${DB_PASS:-marie_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - marie-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js Backend
  backend:
    build: .
    container_name: marie-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=${DB_USER:-marie_user}
      - DB_PASS=${DB_PASS:-marie_password}
      - DB_NAME=${DB_NAME:-marie_erp}
      - JWT_SECRET=${JWT_SECRET:-secret-key}
      - USER_EMAIL=${USER_EMAIL:-costengineapp@gmail.com}
      - USER_PASS=${USER_PASS:-nodwntixywfhmjnf}
      - EMAIL_USER=${EMAIL_USER:-costengineapp@gmail.com}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - marie-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  marie-network:
    driver: bridge 